#!/usr/bin/with-contenv bash

mkdir -p /home/coder/{extensions,data,workspace,.code-server,.ssh}

if [ -n "${SUDO_PASSWORD}" ]; then
  echo "setting up sudo access"
  if ! grep -q 'coder' /etc/sudoers; then
    echo "adding coder to sudoers"
    echo "coder ALL=(ALL:ALL) ALL" >> /etc/sudoers
  fi
  echo "setting sudo password"
  echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd coder
fi

# permissions
chown -R coder:coder \
	/home/coder
